import type { Metadata } from "next";

import "./globals.scss";
import localFont from "next/font/local";

const HeadlineFont = localFont({
  src: "./fonts/new fonts/sawtoncircular-thin-webfont.ttf",
  variable: "--font-headline",
});
const TextFont = localFont({
  src: "./fonts/new fonts/borna-medium-webfont.woff",
  variable: "--font-text",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${HeadlineFont.variable} ${TextFont.variable}`}>
        {children}
        <div className="vertical-line" />
      </body>
    </html>
  );
}
